### ISSUE TITLE
Proposal: Dockerfile

### ISSUE THREAD

**Issue by alexellis** [muesli/beehive#117]
Hi guys,

I'd like to add a Dockerfile for this project to help make this project easier to setup and package. Russell Davis on Twitter has built an image for the Raspberry Pi - so I'd add two Dockerfiles.

https://twitter.com/ukscone/status/840958904653758465

Let me know if you'd merge this change and I'll raise a Pull Request 👍 

Alex

**Comment by alexellis** [comment]
Update: I'd suggest moving the Dockerfile from the docker subdirectory to the root of the project as this is what most projects do and is the least surprising thing to do. It would still be good to add the Dockerfile.armhf for the Raspberry Pi that Russell has tested.

**Comment by muesli** [comment]
Yeah, I would certainly approve that PR. I'm in favor of keeping the Dockerfile in a separate directory though. There's also a PR for snappy and I have the feeling we're only seeing support for more of those build/virt/sandbox systems in the long term. I'd rather have them live happily next to each other in a sub-dir than pollute a project's root-dir.

**Comment by alexellis** [comment]
Docker does not work that way, it has to be in the root of the "context" i.e. the project. It is also a clear indicator that the project has a Dockerfile. I'm a Docker Captain and I completely missed it.

For best practice, there should be a `COPY .` instruction to copy code into the container before initiating the build rather than a `git clone`.

**Comment by muesli** [comment]
Incorporated your suggestions. Thank you!
