### ISSUE TITLE
had to add --net=host to the docker run command on raspberry pi to get access to admin page

### ISSUE THREAD

**Issue by ukscone** [muesli/beehive#118]
I'll readily admit that i'm a complete noob at go & docker and my setup is a tiny bit weird (headless pi, ssh in for compiling/running stuff & vnc when want to use X/browser) but I spent days trying to get a dockerized beehive to let me get to the admin page when running on a raspberry pi & in the end asked for some help. It would always refuse connection from a browser running on the pi until i added the suggested '--net=host' to the docker run command.

i've been told that this is not really a good thing to do though so does anyone have any better ideas?

my dockerfiles are
1. to get a golang base image
http://pastebin.com/tj0WArLQ

2. the beehive docker
http://pastebin.com/t1Bg8PZw

and my now working run command is
docker run --name beehive -d --net=host -p 8181:8181 beehive

**Comment by Joshfindit** [comment]
Note for future solvers of this issue: `--net=host` does not currently work on OSX

**Comment by ukscone** [comment]
i've been messing with beehive on and off over the last few days & found the magic incantation to get it to work how i'd prefer (i trust the others on my LAN, well I mostly trust my wife & son i'm not sure about the cats) so am not bothered about security at the moment and can access the admin page from any computer on my LAN. 

running it with the docker command

docker run --name beehive -d --net=host -p 8181:8181 --entrypoint="beehive" beehive -config /conf/beehive.conf -bind 0.0.0.0:8181 -canonicalurl http://<local ip address>:8181

where local ip address is the ip of the my raspberry pi 

i'm sure if i'd read the docs or used my brain I would have worked this out earlier but i'm posting this so others don't have to faff around trying to workout how to do it

**Comment by muesli** [comment]
Actually ```-canonicalurl http://:8181``` will cause issues. Use the URL you would enter in your browser to reach the admin interface here.

**Comment by ukscone** [comment]
darn <>'s in my c&p removed the ip address i had inbetween them. it did say http://192.168.0.241:8181

**Comment by GabrielAlacchi** [comment]
This should be resolved with pull request #131. Would be nice if @ukscone could confirm that it is in fact fixed. I added -bind ":8181" to the ENTRYPOINT command, which should expose the port to the host network without required --net parameter.

**Comment by ukscone** [comment]
my main beehive is now a PiZeroW without using Docker but will fire up the Docker Pi and report back shortly.

P.S. Beehive on a PiZero works really well for an apiary in your pocket :)

**Comment by ukscone** [comment]
Yes it works as expected on a Pi2

**Comment by ukscone** [comment]
yes it works without the --net=host and as expected and as documented on a Pi2 using Docker

**Comment by GabrielAlacchi** [comment]
Perfect thanks for confirming!
