### ISSUE TITLE
Provided Dockerfile doesn't work with Docker for Mac

### ISSUE THREAD

**Issue by alexellis** [muesli/beehive#119]
**What I expected:**

Beehive on http://localhost:8181 using Docker for Mac 17.03.0-ce.

**What I tried:**

Building with docker/Dockerfile - running with `-p 8181:8181` with or without or `--net=host`.

I suspect this may be something to do with some code binding only to "localhost" ?

Do you guys only test the Dockerfile on a Linux host?

Cheers,

Alex

**Comment by Joshfindit** [comment]
Note for whomever works to resolve this: `--net=host` does not work on OSX ( https://github.com/docker/for-mac/issues/155#issuecomment-285715320 )

**Comment by muesli** [comment]
You can try binding it to other interfaces / addresses: ```./beehive -bind ":8181"```

**Comment by GabrielAlacchi** [comment]
Hey sorry I'm late to the party. I'd love to help! Do you think you could perhaps provide output of running `docker inspect $container_name/id$`. It could possibly provide insight. It is likely that having beehive bind to "0.0.0.0" in the container might solve the issue. In my experience on Ubuntu binding to localhost in the container works fine but I could be wrong.
