### ISSUE TITLE
Having problems with cronbee

### ISSUE THREAD

**Issue by ukscone** [muesli/beehive#122]
This is almost certainly me being a doofus but i'm having problems with cronbee filter to work.

i've tried pretty much all I can think of (not knowing go well/at all) but all I ever get is errors in the logs of similar to below.

time="2017-03-20T15:48:59Z" level=info msg="Event received: Cronbee / time - The time has come ..."
time="2017-03-20T15:48:59Z" level=info msg="    Options: {timestamp string 2017-03-20 15:49:59.00001 +0000 UTC}"
time="2017-03-20T15:48:59Z" level=info msg="Executing chain: ls - ls"
time="2017-03-20T15:48:59Z" level=info msg="    Executing filter: {{test Contains .timestamp 2017}}"
time="2017-03-20T15:48:59Z" level=info msg="Fatal chain event: template: _{{if Contains .timestamp 2017}}true{{end}}:1:14: executing "_{{if Contains .timestamp 2017}}true{{end}}" at <.timestamp>: wrong type for value; expected string; got time.Time"
time="2017-03-20T15:48:59Z" level=info msg="Cronbee has found a time stamp:  2017-03-20 15:54:59.00001 +0000 UTC"

help what am I doing wrong or is cronbee broken at the moment?

**Comment by muesli** [comment]
Are you sure you actually need to filter the event here?

Two things to note:
1. The ```timestamp``` parameter that CronBee emits, is actually the timestamp of the _next_ event that CronBee will get triggered at. That might not be what you expect.
2. You indeed uncovered a bug in the Bee. It currently emits a timestamp, not a string value as documented. I will fix this. _Once_ I did, your filter is almost correct, the only thing you would need to change is encapsulate the string 2017 with quotation marks: ```"2017"```

**Comment by ukscone** [comment]
i'm not actually sure i did need a filter but while still exploring I was just filling in any blank field I see on the chain page.  I did try enclosing in quotation marks but had the same error and the log lines were just the ones at the end after lots of attempts.

and thanks for fixing

**Comment by muesli** [comment]
As mentioned I still need to fix this first for this filter (with quotation marks) to work. I'll nudge you here when I've pushed the fix.

**Comment by CalmBit** [comment]
Should have been fixed by #233 !
