### ISSUE TITLE
Can't access admin UI after building new docker image

### ISSUE THREAD

**Issue by PedroMD** [muesli/beehive#125]
Hello all!

I've just built a new Docker image (latest one does not support twilio bee), but now I can't access the UI. Why is that? I'm inside the container and I can see the latest build for it, inside the config folder (on the repo path). 

I think I must start beehive from the repo path, but, if I do that, I loose its ability to catch signals from the docker stop command, right (as commented in the `ENTRYPOINT` of the Dockerfile).

Any help? 

Great work, btw! :) 

EDIT: wait, looks like I can't even connect to the API, so there is something wrong with the 8181:8181 port binding. It does work for any other `-p x:x` (used for httpbee)

might be duplicate of https://github.com/muesli/beehive/issues/119

**Comment by PedroMD** [comment]
I've uploading the locally (OS X) build image to a private registry of mine so I could try to run it on a Linux machine, but I'm having the exact same problem. Is #119 really OS X related only?

**Comment by muesli** [comment]
Could this be a firewall issue? I've tested the docker setup locally and it seems to work fine.

**Comment by PedroMD** [comment]
Don't believe so, as the original works fine and all other docker images running on the same port... Maybe there is something missing on the dockerfile which we need to make it run properly. Can you share how you build yours? The one on dockerhub works fine, so should this locally build ones, as the only difference is the source code.
