### ISSUE TITLE
(webbee) Possibility to create > 1 path on the same :port ? 

### ISSUE THREAD

**Issue by PedroMD** [muesli/beehive#126]
Hello all!

Currently, it is not possible to create 1 bee on an already existing port when the path is a new one. I do think this is a major issue, as it is not easy to scale... What do you think?

Pedro

**Comment by muesli** [comment]
I assume you're using the latest release 0.2? In git (and the upcoming 0.3), the webbee behavior has already changed:

You now simply configure webbee to listen on an address and it will emit events for all incoming requests, which in turn now include the path as a parameter.

Does that help you?

**Comment by PedroMD** [comment]
Thank you @muesli and sorry for the late response. 

I've tried beehive using the latest provided docker image, but I've then realized the image has not been updated. I will try to run the latest as it sounds like it is now working as originally expected.

**Comment by muesli** [comment]
@PedroMD Any update on that one?

**Comment by PedroMD** [comment]
Not yet as I had to pause this. Will try it again tomorrow, maybe...

**Comment by PedroMD** [comment]
Just tested it and it is working fine fine fine 👍

**Comment by muesli** [comment]
Thanks for confirming!
