### ISSUE TITLE
Prometheus Hive

### ISSUE THREAD

**Issue by muesli** [muesli/beehive#144]
A PrometheusHive could be used to let Beehive events expose data to Prometheus.

**Comment by CalmBit** [comment]
Would you still be interested in having this happen? If you needed someone to work on it, I could give it a shot 😄

**Comment by muesli** [comment]
Absolutely! Prometheus' Go API is rather straight forward and neat, too. Let me know if you run into any issues, I've worked with it before.

This could be really awesome to proxy/export all kinds of metrics data from services that don't natively support Prometheus.

Check out bees/hellobee for a simple "hello world" style bee.

**Comment by CalmBit** [comment]
Alright, my workspace is set up and I'm starting work on it. I'll ping you if I have any questions!

**Comment by muesli** [comment]
Merged to master. Thanks @CalmBit!
