### ISSUE TITLE
I can't actually get the idea of this application

### ISSUE THREAD

**Issue by alymohamedhassan** [muesli/beehive#168]
I was wondering how can I send a notification with python to any smartphone on my network.

I was on another thread but they provided me this link.

Thanks

**Comment by muesli** [comment]
Which thread led you here?

Beehive isn't a Python tool, but a standalone solution/service, which lets you hook up all kinds of events with all other kinds of actions. I'd suggest reading the README and watching the little intro videos linked in there. There's also a bit on info in the wiki here.

The `alertover`, `pushover` and `simplepush` bees let you send notifications to your mobile.

Happy to help with more specific questions regarding the setup, of course.
