### ISSUE TITLE
Build failed on MacOS

### ISSUE THREAD

**Issue by AllenDang** [muesli/beehive#186]
I followed the instruction, run:
make get-deps
make

and here is the error message:
..
go build -tags 'embed' -ldflags '-s -w -X main.Version=0.2.99 -X main.CommitSHA=d94ac35'
# beehive/vendor/github.com/muesli/beehive/api
vendor/github.com/muesli/beehive/api/api.go:71:12: undefined: Asset
vendor/github.com/muesli/beehive/api/api.go:74:12: undefined: Asset
make: *** [build] Error 2

**Comment by deranjer** [comment]
I'm pretty sure it has something to do with their use of go-bindata.

**Comment by muesli** [comment]
I'm afraid I can't reproduce this. Did you try wiping your `vendor` folder entirely and running `make get-deps` again?

Fwiw, we will switch to a different library for embedding binary data, so if it's indeed related to go-bindata, there's a solution on the horizon.

**Comment by muesli** [comment]
@AllenDang @nakata0705 @deranjer Are you trying to build master or v0.2?

**Comment by muesli** [comment]
Could you also check if make correctly executes the command before `go build`?

Should look like
```
/.../src/go/bin/go-bindata --tags embed --pkg api -o api/bindata.go --ignore \\.git assets/... config/...
```

Does `api/bindata.go` exist afterwards?

**Comment by BlackLotus** [comment]
I can reproduce this on two of my systems (both Arch Linux)
> go-bindata --tags embed --debug --pkg api -o api/bindata.go --ignore \\.git assets/... config/...  

doesn't produce any output. Don't know if this is expected behaviour. If there is something I can do to help debug this issue I will

**Comment by muesli** [comment]
@BlackLotus It's not supposed to output anything (to the terminal), but it should create the file api/bindata.go for you. Can you verify that exists?

**Comment by BlackLotus** [comment]
Yup it exists here is the whole file https://gist.github.com/3d675d12cf5b7d88298ce9de687eb655

**Comment by muesli** [comment]
@BlackLotus That looks fine. What issue/error are you facing?

**Comment by BlackLotus** [comment]
The same error as the original poster
```
$ make                                                                                                                                                                                                                                                 git submodule update --init
[ -f /home/thomas/go/bin/go-bindata ] || go get -u github.com/jteeuwen/go-bindata/go-bindata
/home/thomas/go/bin/go-bindata --tags embed --pkg api -o api/bindata.go --ignore \\.git assets/... config/...
go build -tags 'embed' -ldflags '-s -w -X main.Version=0.2.99 -X main.CommitSHA=cf99381'
# beehive/vendor/github.com/muesli/beehive/api
vendor/github.com/muesli/beehive/api/api.go:71:12: undefined: Asset
vendor/github.com/muesli/beehive/api/api.go:74:12: undefined: Asset
make: *** [Makefile:20: build] Fehler 2
```

**Comment by muesli** [comment]
It looks like `dep` vendored beehive itself in `vendor/github.com/muesli/beehive`. That would probably indicate that you're not building Beehive within the designated GOPATH.

Which Go version are you using?
What is your $GOPATH set to?

**Comment by BlackLotus** [comment]
GOPATH is set to ~thomas/go go version 1.10.2.

**Comment by muesli** [comment]
Ok, in that case I would recommend to:

1. Delete your existing `beehive` directory, or at the very least the `vendor` folder inside it.
2. Start with a fresh: `go get github.com/muesli/beehive`
3. cd "$GOPATH/src/github.com/muesli/beehive"
4. make get-deps
5. make

After step 2 you should already have a working beehive binary in your $GOPATH/bin. But to embed the admin interface and extra resources like images, you will need step 3 through 5. See the Troubleshooting section in the README.

It would be interesting to figure out how you ended up in that situation (broken vendor folder) in the first place, though, since I still can't wrap my head around it. Where is your current `beehive` checkout on your disk?

**Comment by BlackLotus** [comment]
Could be that the broken vendor folder somehow came through one of my "workarounds"?  Up until now the way I bould beehive was through
```
git clone https://github.com/muesli/beehive.git
cd beehive
GOPATH=$(pwd) go get -d -v
GOPATH=`pwd` go build
```
Anyway thank you this worked for me and I was able to build beehive without any problems.

**Comment by rubiojr** [comment]
https://github.com/muesli/beehive/pull/213 is trying to fix some recent dep related breakage also.

**Comment by muesli** [comment]
We switched to Go modules in master. This hopefully fixes a bunch of the issues you ran into. Essentially you can simply clone the git repository anywhere now and just run "make".
