### ISSUE TITLE
Implement HTTP basic auth

### ISSUE THREAD

**Issue by dgrr** [muesli/beehive#189]

**Comment by persidskiy** [comment]
Do you guys have such plans? I would like to install it in my private network and share with colleagues.

**Comment by muesli** [comment]
It should be fairly easy to integrate and I'm not opposed to it. I do recommend a simple nginx/apache/caddy reverse proxy with HTTPS around it, though.

**Comment by dgrr** [comment]
Related with https://github.com/muesli/beehive/issues/105

**Comment by dmoonfire** [comment]
For my Nginx setup, I went with:

```
    location / {
        auth_basic "BeeHive";
        auth_basic_user_file "/path/to/beehive.passwd";
    }
```

It was off-the-cuff, but works out for single user site.
