### ISSUE TITLE
Build failure on HEAD

### ISSUE THREAD

**Issue by greenaar** [muesli/beehive#195]
When building via docker against HEAD:

# github.com/Profpatsch/GoOse
src/github.com/Profpatsch/GoOse/extractor.go:264:17: not enough arguments in call to set.New
        have ()
        want (set.SetType)
src/github.com/Profpatsch/GoOse/extractor.go:282:2: cannot use tags (type set.Interface) as type *set.Set in return argument: need type assertion
src/github.com/Profpatsch/GoOse/extractor.go:298:24: not enough arguments in call to set.New
        have ()
        want (set.SetType)
src/github.com/Profpatsch/GoOse/stopwords.go:22:25: cannot use set.New() (type set.Interface) as type *set.Set in assignment: need type assertion
src/github.com/Profpatsch/GoOse/stopwords.go:22:34: not enough arguments in call to set.New
        have ()
        want (set.SetType)
src/github.com/Profpatsch/GoOse/stopwords.go:71:22: not enough arguments in call to set.New
        have ()
        want (set.SetType)
src/github.com/Profpatsch/GoOse/stopwords.go:87:15: cannot use stopWords (type set.Interface) as type *set.Set in assignment: need type assertion
src/github.com/Profpatsch/GoOse/videos.go:30:13: cannot use set.New() (type set.Interface) as type *set.Set in field value: need type assertion
src/github.com/Profpatsch/GoOse/videos.go:30:22: not enough arguments in call to set.New
        have ()
        want (set.SetType)
src/github.com/Profpatsch/GoOse/videos.go:31:22: not enough arguments in call to set.New
        have ()
        want (set.SetType)
src/github.com/Profpatsch/GoOse/videos.go:31:22: too many errors

**Comment by mannp** [comment]
Had the same issue trying to get beehive going with docker.

Was just trying to copy my sia go docker to get it working, but will wait until you have chance to update the official docker.

**Comment by muesli** [comment]
Should be fixed in master.
