### ISSUE TITLE
Dockerized Beehive -> blank webpage

### ISSUE THREAD

**Issue by David-Lor** [muesli/beehive#196]
Whenever I enter Beehive Webui, just a blank webpage is returned:
![image](https://user-images.githubusercontent.com/17401854/44539525-ad0fc600-a704-11e8-8c98-b48b9620d8af.png)
Here's the log:
`time="2018-08-23T16:41:34Z" level=info msg="Registering Resource" Resource=HiveResource ,
time="2018-08-23T16:41:34Z" level=info msg="Registering Resource" Resource=BeeResource ,
time="2018-08-23T16:41:34Z" level=info msg="Registering Resource" Resource=ChainResource ,
time="2018-08-23T16:41:34Z" level=info msg="Registering Resource" Resource=ActionResource ,
time="2018-08-23T16:41:34Z" level=info ,
time="2018-08-23T16:41:34Z" level=info msg="Beehive is buzzing..." ,
time="2018-08-23T16:43:05Z" level=info msg="Handling request" Method=GET URL=/ ,
time="2018-08-23T16:43:05Z" level=info msg="serving config/index.html ... (from )" ,
time="2018-08-23T16:43:05Z" level=info msg="Finished request" Duration=90.866795ms Method=GET Response=200 URL=/ ,
time="2018-08-23T16:43:05Z" level=info msg="Handling request" Method=GET URL=/assets/vendor-be4f842fde3a872763f02c82eea2cca0.css ,
time="2018-08-23T16:43:05Z" level=info msg="serving config/assets/vendor-be4f842fde3a872763f02c82eea2cca0.css ... (from assets/vendor-be4f842fde3a872763f02c82eea2cca0.css)" ,
time="2018-08-23T16:43:05Z" level=info msg="Finished request" Duration=499.962µs Method=GET Response=200 URL=/assets/vendor-be4f842fde3a872763f02c82eea2cca0.css ,
time="2018-08-23T16:43:05Z" level=info msg="Handling request" Method=GET URL=/assets/beehive-admin-9c9bdb140077ec813901397800ee631f.css ,
time="2018-08-23T16:43:05Z" level=info msg="serving config/assets/beehive-admin-9c9bdb140077ec813901397800ee631f.css ... (from assets/beehive-admin-9c9bdb140077ec813901397800ee631f.css)" ,
time="2018-08-23T16:43:05Z" level=info msg="Handling request" Method=GET URL=/assets/vendor-05ef94b42354d0ca8358db1491da1507.js ,
time="2018-08-23T16:43:05Z" level=info msg="serving config/assets/vendor-05ef94b42354d0ca8358db1491da1507.js ... (from assets/vendor-05ef94b42354d0ca8358db1491da1507.js)" ,
time="2018-08-23T16:43:05Z" level=info msg="Finished request" Duration=19.853784ms Method=GET Response=200 URL=/assets/beehive-admin-9c9bdb140077ec813901397800ee631f.css ,
time="2018-08-23T16:43:05Z" level=info msg="Handling request" Method=GET URL=/assets/beehive-admin-3c41873246802b35d4d3d06b42bb4153.js ,
time="2018-08-23T16:43:05Z" level=info msg="serving config/assets/beehive-admin-3c41873246802b35d4d3d06b42bb4153.js ... (from assets/beehive-admin-3c41873246802b35d4d3d06b42bb4153.js)" ,
time="2018-08-23T16:43:05Z" level=info msg="Finished request" Duration=77.897167ms Method=GET Response=200 URL=/assets/beehive-admin-3c41873246802b35d4d3d06b42bb4153.js ,
time="2018-08-23T16:43:06Z" level=info msg="Finished request" Duration=611.072035ms Method=GET Response=200 URL=/assets/vendor-05ef94b42354d0ca8358db1491da1507.js ,
time="2018-08-23T16:43:07Z" level=info msg="Handling request" Method=GET URL=/favicon.ico ,
time="2018-08-23T16:43:07Z" level=info msg="serving config/index.html ... (from favicon.ico)" ,
time="2018-08-23T16:43:07Z" level=info msg="Finished request" Duration=1.402567ms Method=GET Response=200 URL=/favicon.ico ,
time="2018-08-23T16:43:16Z" level=info msg="Handling request" Method=GET URL=/ ,
time="2018-08-23T16:43:16Z" level=info msg="serving config/index.html ... (from )" ,
time="2018-08-23T16:43:16Z" level=info msg="Finished request" Duration=766.524µs Method=GET Response=200 URL=/ ,
time="2018-08-23T16:43:16Z" level=info msg="Handling request" Method=GET URL=/assets/vendor-be4f842fde3a872763f02c82eea2cca0.css ,
time="2018-08-23T16:43:16Z" level=info msg="serving config/assets/vendor-be4f842fde3a872763f02c82eea2cca0.css ... (from assets/vendor-be4f842fde3a872763f02c82eea2cca0.css)" ,
time="2018-08-23T16:43:16Z" level=info msg="Finished request" Duration=1.312087ms Method=GET Response=200 URL=/assets/vendor-be4f842fde3a872763f02c82eea2cca0.css ,
time="2018-08-23T16:43:16Z" level=info msg="Handling request" Method=GET URL=/assets/vendor-05ef94b42354d0ca8358db1491da1507.js ,
time="2018-08-23T16:43:16Z" level=info msg="serving config/assets/vendor-05ef94b42354d0ca8358db1491da1507.js ... (from assets/vendor-05ef94b42354d0ca8358db1491da1507.js)" ,
time="2018-08-23T16:43:16Z" level=info msg="Handling request" Method=GET URL=/assets/beehive-admin-9c9bdb140077ec813901397800ee631f.css ,
time="2018-08-23T16:43:16Z" level=info msg="serving config/assets/beehive-admin-9c9bdb140077ec813901397800ee631f.css ... (from assets/beehive-admin-9c9bdb140077ec813901397800ee631f.css)" ,
time="2018-08-23T16:43:16Z" level=info msg="Handling request" Method=GET URL=/assets/beehive-admin-3c41873246802b35d4d3d06b42bb4153.js ,
time="2018-08-23T16:43:16Z" level=info msg="serving config/assets/beehive-admin-3c41873246802b35d4d3d06b42bb4153.js ... (from assets/beehive-admin-3c41873246802b35d4d3d06b42bb4153.js)" ,
time="2018-08-23T16:43:16Z" level=info msg="Finished request" Duration=41.114975ms Method=GET Response=200 URL=/assets/beehive-admin-9c9bdb140077ec813901397800ee631f.css ,
time="2018-08-23T16:43:17Z" level=info msg="Finished request" Duration=82.789353ms Method=GET Response=200 URL=/assets/beehive-admin-3c41873246802b35d4d3d06b42bb4153.js ,
time="2018-08-23T16:43:17Z" level=info msg="Finished request" Duration=526.459475ms Method=GET Response=200 URL=/assets/vendor-05ef94b42354d0ca8358db1491da1507.js ,
time="2018-08-23T16:43:18Z" level=info msg="Handling request" Method=GET URL=/favicon.ico ,
time="2018-08-23T16:43:18Z" level=info msg="serving config/index.html ... (from favicon.ico)" ,
time="2018-08-23T16:43:18Z" level=info msg="Finished request" Duration=1.537928ms Method=GET Response=200 URL=/favicon.ico ,
time="2018-08-23T16:43:18Z" level=info msg="Handling request" Method=GET URL=/favicon.ico ,
time="2018-08-23T16:43:18Z" level=info msg="serving config/index.html ... (from favicon.ico)" ,
time="2018-08-23T16:43:18Z" level=info msg="Finished request" Duration=1.286447ms Method=GET Response=200 URL=/favicon.ico ,`

**Comment by muesli** [comment]
Please use the "-canonicalurl" and "-bind" parameters if you want to reach Beehive from a host other than localhost.

**Comment by dendiz** [comment]
I faced the same issue and didn't want to setup a golang build environment. The problem is that the request to load javascript are made to localhost, which is different than the server you have beehive running on. As a workaround what I did was forward 8181 on localhost to the server I had beehive.


for windows it's:
<code>
netsh interface portproxy add v4tov4 listenport=8181 listenaddress=localhost connectport=8181 connectaddress=192.168.0.62
</code>


and to delete
<code>
netsh interface portproxy delete v4tov4 listenport=8181 listenaddress=localhost
</code>


for Linux you can setup an nginx reverse proxy or mess around with iptables to do the same.

**Comment by revil-O** [comment]
i use beehive in a docker container on my synology nas. at creation of new container in settings -> environment is a cmd option below 'entry-point' : simply put in the following code: 

-canonicalurl http://<your url here>:8181

an start the container. in a browser navigate to <your url here>:8181 and everything works like a charme. 

Regards revil.O

**Comment by ssbarnea** [comment]
I was hit by the same bug and based on the commit history, I was expecting to be able to use CANONICAL_URL environment variable to make the container work. Guess, what the container still servers stuff using its localhost address even after defining this variable, so the bug is perfectly valid.

The container published on docker, must be able to load CANONICAL_URL and use it, without the need to rebuild the container.

**Comment by muesli** [comment]
Please try the latest docker image from fribbledom/beehive, or try the `Dockerfile` from master.

**Comment by esturniolo** [comment]
Sorry guy, but I've the same situation with no luck. I've just made a pull from fribbledom/beehive and I still get the blank screen.
I can't figure out where I should add the canonical url line to make it work.

**Comment by muesli** [comment]
@esturniolo You can add it to your `docker run` command, simply add `-e CANONICAL_URL="http://host:port"`.

Which browser do you use, and which address are you trying to reach Beehive at?

**Comment by esturniolo** [comment]
Thanks for your fast response!
I'm using Chrome (tried with Firefox and Safari too without any luck)

I'm trying to run it like this: 
`docker run -e http://192.168.0.37:8181 --name beehive -d -p 8181:8181 fribbledom/beehive`

But I still got the blank page.

**Comment by muesli** [comment]
You missed the "CANONICAL_URL" part:

```
docker run --name beehive -d -e CANONICAL_URL="http://192.168.0.37:8181" -p 8181:8181 fribbledom/beehive
```

Then access `http://192.168.0.37:8181` in your browser.

**Comment by esturniolo** [comment]
Finally!!!
Is now working! 
`docker run --name beehive -d -p 8181:8181 -e CANONICAL_URL="http://192.168.0.37:8181" fribbledom/beehive` was the correct command to run

**Comment by esturniolo** [comment]
> You missed the "CANONICAL_URL" part:
> 
> ```
> docker run --name beehive -d -e CANONICAL_URL="http://192.168.0.37:8181" -p 8181:8181 fribbledom/beehive
> ```
> 
> Then access `http://192.168.0.37:8181` in your browser.

Yes. My mistake.
Thanks a lot @muesli

**Comment by Zodyart** [comment]
> @esturniolo You can add it to your `docker run` command, simply add `-e CANONICAL_URL="http://host:port"`.
> 
> Which browser do you use, and which address are you trying to reach Beehive at?

You wisdom stands strong even in 2022 you have helped me quickly, thank you!
