### ISSUE TITLE
Using " or ' with "Execute command" bee

### ISSUE THREAD

**Issue by Larpon** [muesli/beehive#198]
I'm trying to run a custom script with a bee from the `Execute command` hive via a `Cron` bee.

I'm trying to pass {{.timestamp}} as a parameter to the script.
But the script only get the first part of the date up until the space. I've tried to escape the `"` with no luck.

`/path/to/script "{{.timestamp}}"`
My script echoes argument `$1` to file in `/tmp/`
Contents are: `"2018-10-05` ???

How do we escape the `"` character?

**Comment by muesli** [comment]
You would have to escape the quotes by prepending them with a backslash, like `\"`.
