### ISSUE TITLE
make get-deps: No versions of github.com/google/go-github met constraints

### ISSUE THREAD

**Issue by LorenzoAncora** [muesli/beehive#204]
Installation of the latest version fails with this error:

$ make get-deps
> dep ensure
Solving failure: No versions of github.com/google/go-github met constraints:
        v15.0.0: Could not introduce github.com/google/go-github@v15.0.0, as its subpackage github.com/google/go-github/v18/github is missing. (Package is required by (root).)
        v18.2.0: Could not introduce github.com/google/go-github@v18.2.0, as it is not allowed by constraint ^15.0.0 from project beehive.
        v18.1.0: Could not introduce github.com/google/go-github@v18.1.0, as it is not allowed by constraint ^15.0.0 from project beehive.
        v18.0.0: Could not introduce github.com/google/go-github@v18.0.0, as it is not allowed by constraint ^15.0.0 from project beehive.
        v17.0.0: Could not introduce github.com/google/go-github@v17.0.0, as it is not allowed by constraint ^15.0.0 from project beehive.
        v16.0.0: Could not introduce github.com/google/go-github@v16.0.0, as it is not allowed by constraint ^15.0.0 from project beehive.
        v14.0.0: Could not introduce github.com/google/go-github@v14.0.0, as it is not allowed by constraint ^15.0.0 from project beehive.
        v13.0.0: Could not introduce github.com/google/go-github@v13.0.0, as it is not allowed by constraint ^15.0.0 from project beehive.
        v12.0.0: Could not introduce github.com/google/go-github@v12.0.0, as it is not allowed by constraint ^15.0.0 from project beehive.
        v11.0.0: Could not introduce github.com/google/go-github@v11.0.0, as it is not allowed by constraint ^15.0.0 from project beehive.
        v10.0.0: Could not introduce github.com/google/go-github@v10.0.0, as it is not allowed by constraint ^15.0.0 from project beehive.
        v9.0.0: Could not introduce github.com/google/go-github@v9.0.0, as it is not allowed by constraint ^15.0.0 from project beehive.
        v8.0.0: Could not introduce github.com/google/go-github@v8.0.0, as it is not allowed by constraint ^15.0.0 from project beehive.
        v7.0.0: Could not introduce github.com/google/go-github@v7.0.0, as it is not allowed by constraint ^15.0.0 from project beehive.
        v6.0.0: Could not introduce github.com/google/go-github@v6.0.0, as it is not allowed by constraint ^15.0.0 from project beehive.
        v5.0.0: Could not introduce github.com/google/go-github@v5.0.0, as it is not allowed by constraint ^15.0.0 from project beehive.
        v4.0.0: Could not introduce github.com/google/go-github@v4.0.0, as it is not allowed by constraint ^15.0.0 from project beehive.
        v3.0.0: Could not introduce github.com/google/go-github@v3.0.0, as it is not allowed by constraint ^15.0.0 from project beehive.
        v2.0.0: Could not introduce github.com/google/go-github@v2.0.0, as it is not allowed by constraint ^15.0.0 from project beehive.
        master: Could not introduce github.com/google/go-github@master, as it is not allowed by constraint ^15.0.0 from project beehive.
        revert-844-teamreview: Could not introduce github.com/google/go-github@revert-844-teamreview, as it is not allowed by constraint ^15.0.0 from project beehive.
make: *** [Makefile:29: get-deps] Error 1

Using: `Debian 4.18.6-1 - ARM64 (Raspberry Pi 3 B in aarch64 mode)`

**Comment by LorenzoAncora** [comment]
@muesli 
Is this an unsolvable problem? :-)

**Comment by muesli** [comment]
@LorenzoAncora Do a `git submodule update --init` in beehive's directory. That should pull in all the vendored sources from the repository `beehive-vendor`.

We'll switch from `dep` to go modules in the near future.

**Comment by muesli** [comment]
Are you not compiling this from within your $GOPATH?

**Comment by LorenzoAncora** [comment]
> Are you not compiling this from within your $GOPATH?

@muesli yes. My GOPATH is `/usr/local` and I am compiling Beehive from `/usr/local/src/beehive` (the directory with the downloaded sources).

**Comment by muesli** [comment]
That's probably the issue, your GOPATH structure is wrong. The beehive sources need to live in $GOPATH/src/github.com/muesli/beehive to be compiled.

**Comment by LorenzoAncora** [comment]
<sup>@muesli</sup>
> The beehive **sources need to live in $GOPATH/src/github.com/muesli/beehive** to be compiled.

After following this new directive Beehive gets compiled correctly and serves the admin interface without errors.
**Thank you for your support.**

---

> That's probably the issue, **your GOPATH structure is wrong**.

...perhaps it is more appropriate to say that the installation instructions are not correct.

![Installation instructions](https://i.postimg.cc/VLM8PFM6/Istantanea-2018-11-03-22-02-46.png)
![](https://i.postimg.cc/4xZrkRsL/Istantanea-2018-11-03-22-05-53.png)

...there is no indication of this peculiar _installation_ requirement in the _installation_ instructions.
Perhaps it is appropriate to replace:

```
You currently have to start beehive from within $GOPATH/src/github.com/muesli/beehive in order for it to find all the resources for the admin interface
```

...with:
```
You currently have to install beehive in $GOPATH/src/github.com/muesli/beehive and start it from there in order for it to find all the resources for the admin interface
```

A simple modification like this, combined with a small note in the installation instructions shown above should solve the problem for everyone.

**Comment by LorenzoAncora** [comment]
@muesli I'm pushing the changes made to the README but `slackbee` does not work properly. I need you to approve the push request (#207) manually.
