### ISSUE TITLE
Is this repository dead? 💀

### ISSUE THREAD

**Issue by LorenzoAncora** [muesli/beehive#211]
I see that there are 9 push requests pending and the oldest **dates back to 8 April 2017**.
Is there still interest in developing Beehive or maybe the author prefers to devote himself to something else?

It is currently frustrating and confusing to insert new commits due to unresolved Issue #210 that marks good commits as invalid.

**Comment by muesli** [comment]
Nope, as discussed with you on IRC, I just didn't have the time to make the proper switch to Go modules before. Done in master now.
