### ISSUE TITLE
bee.LogDebugF

### ISSUE THREAD

**Issue by CalmBit** [muesli/beehive#237]
It'd be really cool to be able to put in some diagnostic information as debug-level logging, especially for situations in which someone is having an issue figuring out what's wrong with a bee. We've got a lot of debug information to report, but cluttering the log with this normally seems rather poor practice. So why not have a way to log debug statements?

**Comment by muesli** [comment]
Yeah, I must admit I'm not sure why I didn't add that in the first place. Resolved by your own PR that I just merged into master!
