### ISSUE TITLE
Beehive support this triggers? 

### ISSUE THREAD

**Issue by reilue** [muesli/beehive#258]
Hi. I'm fascinated with beehive, and I wonder if such triggers are support:
- Read Email ( e.g. Google)
- Interact with Google Spreadsheet for writing a cell

**Comment by muesli** [comment]
We could add an IMAP hive, that would make it work with all kinds of mail services.
I'm afraid I have no idea if there's a public API for Google Spreadsheets (even though I would assume there is), though.

We should probably split this up into two separate tickets.

**Comment by reilue** [comment]
I would love to contribute but my background is with Python & JS. 😞

The tickets could be something like this. 

- Trigger for Google Mail
https://developers.google.com/gmail/api/guides/

- Trigger for Google Spreadsheet 
https://developers.google.com/sheets/api/reference/rest/

Or something that you may find more appropriate.

**Comment by CalmBit** [comment]
Gonna see if I can get these two up and running soon 😄

**Comment by helmut72** [comment]
A standard IMAP connection would be cool. GMail is Google only.

**Comment by CalmBit** [comment]
I split this up into two separate tickets, as seen above! Closing for now.
