### ISSUE TITLE
Facebook bee setup problem

### ISSUE THREAD

**Issue by Invertisment** [muesli/beehive#264]
I wanted to fiddle with facebook bee and before I could even try it out I got an error.
It's related to the deprecated post API.

I am in no hurry to fix anything and this doesn't impact me, but it would be nice for it to work.

https://www.nextscripts.com/news/2018/04/facebook-error-invalid-scopes-publish_actions/

**Comment by CalmBit** [comment]
Could you post the error here? I'd like to debug this and see what's going on.

**Comment by Invertisment** [comment]
I've tried again and this time I noticed that I didn't set my fb app to "live" (I haven't created any fb apps too).
With this being out of the way it could work but now I get an error about the domain of the app (in lithuanian):

Nepavyksta atverti nuorodos: Nuorodos domenas nėra įtrauktas į programėlės domenų sąrašą. Programėlės nustatymuose, lauke Programėlės Domenai, pridėkite visus programėlės domenus ir subdomenus, ir jūs sėkmingai galėsite atidaryti šią nuorodą.

As I understand this basically means that I have to add the domain of the app to the `Domains`, which I already tried for a couple of times. And probably as I've tried to make it work with `localhost` and `127.0.0.1` they may not work at all.

As I've doing this only for exploration I would like to have any tutorials that may be useful. Probably it would be a nice addition. 
Thanks.

**Comment by CalmBit** [comment]
[This](https://wp-native-articles.com/blog/news/how-to-fix-facebook-apps-error-cant-load-url-domain-url-isnt-included-apps-domains/) seems to cover this error pretty well. I'll have to research it more, but the HTTPS requirement might be the first place to start.

**Comment by pbek** [comment]
> Invalid Scopes: publish_actions. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions

I did get the same error message when trying to retrieve an access token.
The facebook hive tries to get `publish_actions` permission. This permission doesn't seem to exist any more.
I cannot find them on https://developers.facebook.com/docs/facebook-login/permissions or in the permission list on https://developers.facebook.com/tools/explorer/.

**Comment by pbek** [comment]
I valid permission could be [pages_manage_posts](https://developers.facebook.com/docs/permissions/reference/pages_manage_posts).

**Comment by pbek** [comment]
I replaced the permissions in Beehive which allowed me to get an access token, but when I tried to post a message to my Facebook page I got an error:

```
ERRO[0490] [Facebook]: Error: [message:(#200) If posting to a group, requires app being installed in the group, and \
          either publish_to_groups permission with user token, or both pages_read_engagement \
          and pages_manage_posts permission with page token; If posting to a page, \
          requires both pages_read_engagement and pages_manage_posts as an admin with \
          sufficient administrative permission] [type:OAuthException] [code:200] [subcode:0] 
```

**Comment by pbek** [comment]
I tried to use the scopes `"public_profile", "pages_manage_posts", "publish_to_groups", "pages_read_engagement"` but wasn't able to get an access token on localhost because https was enforced by Facebook.

**Comment by pbek** [comment]
I created a pull requests for the scopes: https://github.com/muesli/beehive/pull/345
