### ISSUE TITLE
Algebraic operation Filters

### ISSUE THREAD

**Issue by muesli** [muesli/beehive#28]
Anyone with some 8th grade maths knowledge could do this ;-)

**Comment by muesli** [comment]
This can be done with the standard 'template' filter now.

**Comment by Skrylar** [comment]
Does this include some of the statistical filters a la Huginn? Examples:

- Stores the last value and outputs the relative change of value
- Stores a window of values and outputs events if something falls outside N deviations
- Accumulates entries then empties in to a template when manually triggered (used for digests; events accumulate and then get dispatched in single big e-mails)

Or do those things deserve other tickets / are already things?

**Comment by muesli** [comment]
@Skrylar I'm not sure if that's within Beehive's scope (even though a specialized hive could do it). Certainly worth a separate ticket.
