### ISSUE TITLE
[Windows] Configuration file is not created

### ISSUE THREAD

**Issue by crile** [muesli/beehive#287]
Hi,

I simply run "beehive.exe" but nothing is created in the current directory.

```
$ beehive -version
Beehive 0.3.2 (c66102d5e32bffbad9124d41ae2ffd203ee55399)

$ beehive -help
Usage of beehive.exe:
  -bind string
        Which address to bind Beehive's API & admin interface to (default "localhost:8181")
  -canonicalurl string
        Canonical URL for the API & admin interface (default "http://localhost:8181")
  -config string
        Config-file to use (default "./beehive.conf")
  -version
        Beehive version
```

**Comment by muesli** [comment]
Did you connect to the Admin interface and created some Bees and Chains?

**Comment by crile** [comment]
Yes I did. I even try with "`-config`" flag.
I stop the server with "CTRL+C".
The file is not generated during the startup ?

**Comment by muesli** [comment]
@crile Could you paste Beehive's output just before & after hitting CTRL-C?

**Comment by crile** [comment]
Extract of the console output below.

```
INFO[0213] Handling request                              Method=GET URL=/v1/bees
INFO[0213] Finished request                              Duration="996.8µs" Method=GET Response=200 URL=/v1/bees
INFO[0217] Got signal: interrupt                        
INFO[0217] Storing config...                    
```

I attached the log file
[beehive.log](https://github.com/muesli/beehive/files/4448998/beehive.log)

**Comment by crile** [comment]
Sorry, it is not a beehive bug.

I use an alternative console (`nyagos.exe`), and I think that the kill signal force `beehive.exe` to stop so it doesn't have the time to write its configuration file.

It is the first time that I encounter this kind of issue.

Thanks anyway.

**Comment by muesli** [comment]
Interesting! So you can't reproduce this when starting from a "normal" cmd? There's already a PR which changes this behavior a bit and stores the config before shutdown. I guess this should improve the situation, even though it's clearly never ideal if the console kills the process while it's shutting down.

**Comment by crile** [comment]
Yes, "CRTL+c" in "normal" cmd works properly. Thanks.
