### ISSUE TITLE
Pastebin Bee

### ISSUE THREAD

**Issue by grindhold** [muesli/beehive#30]
A bee that can post stuff to http://pastebin.com and react to stuff being posted.

**Comment by tpltnt** [comment]
maybe leverage [go_pastebin](https://github.com/glaxx/go_pastebin)

**Comment by seblw** [comment]
I can start working on this.

**Comment by muesli** [comment]
@seblw: Since @glaxx has never had the time to start working on this, that would be great!

**Comment by seblw** [comment]
@muesli ok, from what I've seen in pastebin api, posting snippets should be easy to implement, but reacting to stuff being posted on pastebin should be rather done using google bee ( #16)

**Comment by muesli** [comment]
Reacting to pastebin updates isn't a top priority - even though I would try to solve it within the Pastebin Bee itself. Ideally _without_ polling the pastebin in intervals.

That said, I'd focus on adding a new pastebin and appending to an existing pastebin (if allowed by API).
