### ISSUE TITLE
Watch new releases in GitHub bee

### ISSUE THREAD

**Issue by moqmar** [muesli/beehive#318]
It would be awesome if the GitHub bee had a trigger for new releases, so it could be used to trigger builds of dependent software.

**Comment by rubiojr** [comment]
Should be easy to add to the existing bee.

@moqmar you could try to use the RSS bee in the meantime to monitor the atom feed for a given project (i.e. https://github.com/muesli/beehive/releases.atom).

**Comment by Zykino** [comment]
It’s what I have done, but since github does not show the RSS feed prominently, a sample showing how to follow beehive’s releases (and show a desktop notification ?) can be a nice "hello world" example.
