### ISSUE TITLE
100% CPU usage if using Twitter bee

### ISSUE THREAD

**Issue by Phoenix616** [muesli/beehive#335]
It seems to be using 100% of one core/thread once I enable a Twitter bee even without using any kind of chain which would react on twitter actions (I only use it to send tweets)

**Comment by muesli** [comment]
Thanks for the heads up. That may be related to Twitter shutting down several API endpoints. Investigating.

**Comment by pbek** [comment]
@muesli, I was able to post to Twitter, but two cores of my server are at 100%! Were you already able to take a look at the Twitter Hive? Reacting to Twitter likes didn't seem to work for me, `Last Event` always says `never` for me.

**Comment by pbek** [comment]
@muesli, the only thing that runs infinitely in the Twitter Bee seems to be:

https://github.com/muesli/beehive/blob/f6ac3ac98e38727fdf0255f85ee26ab4298c3c7a/bees/twitterbee/twitterbee.go#L290-L295

**Comment by pbek** [comment]
Although `item` seems to be `nil` a lot (all the time?).

**Comment by pbek** [comment]
I was able to fix the 100% CPU problem, but reacting to a like still doesn't seem to work for me. At least posting tweets is still working...

https://github.com/muesli/beehive/pull/347

**Comment by pbek** [comment]
Last commit on https://github.com/ChimeraCoder/anaconda (library that handles the Twitter API) was 2 years ago. 😬

**Comment by pbek** [comment]
The user stream <https://userstream.twitter.com/1.1/user.json> is [retired since more than 2 years](https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/subscribe-account-activity/migration/us-ss-migration-guide).

The replacements seem to be the "Premium Account Activity API" and "Enterprise Account Activity API". 😁  At least posting tweets still seems to work.

**Comment by muesli** [comment]
Yeah, I guess most people stopped using the Twitter API at that point, myself included. I'm actually one of the anaconda maintainers, but development has pretty much ceased when Twitter shut down most of their API for public use.

**Comment by pbek** [comment]
Posting still works (and I plan to use it), only the user stream is shut down.

**Comment by muesli** [comment]
I've just removed the user stream from the Twitter hive, as it's not supported by Twitter anymore. This in turn means the TwitterBee now only supports posting, following & unfollowing other users. There are no more events we can currently support. What a shame.

This also fixes this issue.

**Comment by pbek** [comment]
Awesome, @muesli! Are you also pushing the changes to Docker-Hub so I can use your container again? 😁

**Comment by muesli** [comment]
If you use beehive:latest, this will automatically be built every time someone pushes to git master.

**Comment by pbek** [comment]
`image: fribbledom/beehive` should get the latest, thank you very much!

**Comment by georgkrause** [comment]
If thats resolved, please consider updating https://github.com/muesli/beehive/wiki/Twitter
