### ISSUE TITLE
Email hive doesn't work with unauthenticated smtp servers

### ISSUE THREAD

**Issue by pbek** [muesli/beehive#344]
I'm using a docker container only beehive has access to as smtp server to send myself emails, but the admin interface doesn't allow you to skip user credentials.

(Thank you for this great project, I want to automate some things with it for https://github.com/pbek/QOwnNotes.)

**Comment by pbek** [comment]
I found out you can get around it by entering some text and removing it again later. That way it works.

**Comment by muesli** [comment]
Ok, we should probably mark these options as non-mandatory.

**Comment by corrantho** [comment]
I think this issue can now be closed.

**Comment by pbek** [comment]
Nice, thank you!
