### ISSUE TITLE
Missing URL in messages transmitted from telegram to IRC

### ISSUE THREAD

**Issue by Sakrecoer** [muesli/beehive#357]
I set up a chain to take a message sent to telegram bot to be delivered to an IRC channel. However if the text of the message contains an URL, `{{.text}}` is not  transmitting this URL to IRC.

**Comment by Sakrecoer** [comment]
This seems to be specific to the IRC bee. Using `{{.text}}` with the mastodon or the telegram bee considers the URL as part of the text as expected.

**Comment by muesli** [comment]
Is this URL exceeding the line length of your IRC server?

**Comment by Sakrecoer** [comment]
Thank you for your quick response!

I believe it isn't too long. But you made me understand what happened: line
breaks!

For reference here is the format of a test messages:

```
first line
second line
http://example.url
```

Only the first line came through! Which might be unfortunate in my usecase,
but makes total sense.

Sorry for the noise and many thanks for looking into this.

**Comment by muesli** [comment]
In that case we should probably split the text by `\n` and send the lines out individually.

**Comment by muesli** [comment]
I've just pushed a commit that should fix this situation: we're splitting each outgoing message by the newline character now.

**Comment by Sakrecoer** [comment]
wow! how quick!? \o/
Thank you very much!

There's not much i can offer in return of your precious dedication, but i
have started writing documentation on how to set up the telegram and
mastodon bees for the wiki <3

**Comment by muesli** [comment]
Kind words and the courage to open a ticket is a lot more than most people offer these days :smiley:

So "thank you very much" right back at you :heart:
