### ISSUE TITLE
lock files out of date

### ISSUE THREAD

**Issue by Profpatsch** [muesli/beehive#361]
```
github.com/blend/go-sdk v2.0.0+incompatible h1:FL9X/of4ZYO5D2JJNI4vHrbXPfuSDbUa7h8JP9+E92w=
github.com/blend/go-sdk v2.0.0+incompatible/go.mod h1:3GUb0YsHFNTJ6hsJTpzdmCUl05o8HisKjx5OAlzYKdw=
```

blend/go-sdk renamed their tag to `legacy-v2.0.0` and now the lock file is broken, see https://github.com/nix-community/vgo2nix/issues/48

I am uncertain how `go get` still works, they might be falling back to just ignoring the hash (which is a security nightmare, but what do I know).

**Comment by muesli** [comment]
Bumped the transitive dep in kmeans, gamut & beehive.
