### ISSUE TITLE
Telegram bee stopped working

### ISSUE THREAD

**Issue by Sakrecoer** [muesli/beehive#380]
As of august 6th the telegram bee stopped working. I suspect there might have been some change in the API. I've tested with a new API token, but i'm not too sure how to debug it as i don't seem to be able to locate the logs anymore :/

**Comment by corrantho** [comment]
Hi @Sakrecoer, could you please give instructions on how to reproduce the issue? I've just created a new telegram bee and it seems to be ok.

**Comment by corrantho** [comment]
Hi @Sakrecoer, could you please provide instructions on how to reproduce the issue? I created a new telegrambee and could not reproduce the bug on my side.
The bot is correctly sending a message to my chat_id.
Please provide the error log.

Thank you.

**Comment by Sakrecoer** [comment]
@corrantho Sure. But where do i find the error logs?

**Comment by muesli** [comment]
@Sakrecoer There's no separate logfile. Simply start beehive, and it will log on `stdout`. If you're running beehive as a `systemd` service, check `journalctl`.

**Comment by Sakrecoer** [comment]
@muesli of course... silly me lol...

Well, this is very weird. The bot is authorized on telegram. no error messages at all. Filters are executing fine. No error messages no nothing happens.

```
aug 18 10:05:29 pi7 beehive[20230]: INFO[0166]         Executing filter:  {{test eq .user_id "numer_redacted}}
aug 18 10:05:29 pi7 beehive[20230]: INFO[0166]         Executing filter: {{test Contains .text "#hashtag"}}
```

**Comment by Sakrecoer** [comment]
wow.... i have no idea what has happened. It's like the Nth time i restart it. I did it again, but this time it sent out the last event i tried to deliver _before_ reboot. (sending a message to the telegram bot for it to deliver them in a channel) 

But there's nothing about it in `journalctl`

**Comment by Sakrecoer** [comment]
Closing this, everything seems to be working again. Probably something fishy with the system my beehive is running on.
