### ISSUE TITLE
HtmlExtractBee misses everything before a “-”

### ISSUE THREAD

**Issue by Profpatsch** [muesli/beehive#42]
Example: 

```
https://www.youtube.com/watch?v=RXPg0yINxWU
```

evaluates to

```
[ It's Time (Matoma Tropical Remix) | www.youtube.com | https://i.ytimg.com/vi/RXPg0yINxWU/maxresdefault.jpg ]
```

but its full title is

```
Imagine Dragons - It's Time (Matoma Tropical Remix)
```

**Comment by muesli** [comment]
To be honest, I think that's intentional by the html metadata parser we use, due to so many sites doing something like "foobar.com - The real article title".

Not sure if we want to get overly clever and add a special case for YouTube, or even take the "|" into account.

**Comment by Profpatsch** [comment]
This happens a *lot*.

**Comment by muesli** [comment]
Patches are welcome :-p

**Comment by muesli** [comment]
Decided this should be fixed upstream as it isn't a specific problem of Beehive / HtmlExtractBee.
