### ISSUE TITLE
MumbleBee

### ISSUE THREAD

**Issue by grindhold** [muesli/beehive#44]
Bee that connects to mumble services.

Possible unfinished library to complete and use would be https://github.com/handymic/mumgo
Other option would be to put together a own new mumble-go-lib.

**Comment by momo-aux** [comment]
what about: 
https://github.com/layeh/gumble
https://godoc.org/layeh.com/gumble/gumble

**Comment by muesli** [comment]
Yeah, I'd prefer gumble, as it looks like it's actively maintained and much more complete.

**Comment by muesli** [comment]
Done in master.

**Comment by grindhold** [comment]
10/10. top githubber. would do business again with.
