### ISSUE TITLE
Move config into a separate repository and make it a git submodule

### ISSUE THREAD

**Issue by muesli** [muesli/beehive#66]
Two separate projects, two repositories. Easier to test (Travis limitations), easier to handle.

**Comment by dschmidt** [comment]
"git submodul" and "easier to handle" in one sentence, wow :-)

**Comment by muesli** [comment]
Right? ;-) Seriously though, you can only have one Travis config per repo, so that alone justifies separating the Go project root from the Ember.js one.

**Comment by dschmidt** [comment]
Sure i'm obviously kidding :)

**Comment by muesli** [comment]
Admin interface lives here now: https://github.com/muesli/beehive-admin

**Comment by muesli** [comment]
Done for v0.2
