### ISSUE TITLE
Add url parameter to Twitter events

### ISSUE THREAD

**Issue by muesli** [muesli/beehive#70]
```url``` should point to the canonical Twitter URL of the tweet.

**Comment by seblw** [comment]
hi, could you explain more what needs to be done here?

**Comment by muesli** [comment]
Right now the twitter events usually contain the tweet/event's author and the content of the tweet. For many use-cases it would be nice to also get the url of the tweet on twitter.com - so you can link to it.

All that really needs be done is retrieving the URL from the API and passing it along with the event, like the other params.

**Comment by seblw** [comment]
Ok, thanks, I'll work on it.

**Comment by muesli** [comment]
Nice! Should you have more questions, don't hesitate to post them here - or join us on Gitter/IRC.

**Comment by seblw** [comment]
#84
