### ISSUE TITLE
Add running in a Docker container as an installation option

### ISSUE THREAD

**Issue by selenium-tester** [muesli/beehive#71]
It would be great to see this running in a Docker container as an alternative to having to setup an entire Go environment just to try it out.

**Comment by GabrielAlacchi** [comment]
@muesli I could tackle this. Just to be sure however, only port 8181 actually needs to be exposed. Also which files need to be made persistent? Correct me if I'm wrong but the beehive.conf file is the only one from what I can see.

**Comment by muesli** [comment]
I'd absolutely appreciate your help here!

Correct, port 8181 is currently the only exposed port (note that it's currently exposed on loopback only!), serving API and HTML/CSS/images.

beehive.conf is indeed the only file that needs to be made persistent. It stores the entire config, including all bee-options and chains.
