### ISSUE TITLE
TwilioBee

### ISSUE THREAD

**Issue by jamesbvaughan** [muesli/beehive#81]
Bee that lets you send yourself SMS messages through Twilio.

Could possibly use one of these Twilio/Go libraries:
https://github.com/sfreiberg/gotwilio
https://github.com/carlosdp/twiliogo

**Comment by jamesbvaughan** [comment]
I'm new to Go but would be down to work on adding this in the next week or two.

**Comment by muesli** [comment]
Great! Should you need any help, just let us know!

**Comment by jamesbvaughan** [comment]
Alright, I've added this in #91

**Comment by muesli** [comment]
Thanks James!
