### ISSUE TITLE
GitHub Bee

### ISSUE THREAD

**Issue by muesli** [muesli/beehive#9]
Bee triggering events on GitHub commits / changes.

**Comment by PenguWin** [comment]
Im currently working on a Github bee which is also including 'social' actions like (un)staring, (un)watching repositories. 
I'll try to finish it as fast as possible.

**Comment by smazurov** [comment]
would also love:

- pr events (new pr, closed, label, etc)
- pr actions (close, mark as reviewed [success,comment,decline], add label, assign)
- project actions (add card, move card from column to column)

**Comment by muesli** [comment]
Kudos go to @PenguWin for bootstrapping the whole thing. I just finished it.

**Comment by muesli** [comment]
@smazurov We covered the basic events & actions for now. I'd suggest opening separate tickets for further events & actions you would like to see. Thank you!

**Comment by rubiojr** [comment]
:zap::zap::zap:
