### ISSUE TITLE
Configuration of hostname

### ISSUE THREAD

**Issue by ad-m** [muesli/beehive#95]
Hello,

I would like configure beehive on server. I setup domain, use reverse proxy, but there is still references to "http://localhost:8181". It ignore my custom domain, so the requests fail. I am unable to set up beehive on server due that (screen was empty).

Here is chromium log:
![zaznaczenie_0375](https://cloud.githubusercontent.com/assets/3618479/23091038/af77646c-f5ac-11e6-8755-589349429ca6.png)

It looks ``localhost:8181`` was hardcoded in some places of source code:

* https://github.com/muesli/beehive/blob/f13201776bfb467fa7342babcf5b0d7b26374416/api/api.go#L76
* https://github.com/muesli/beehive/blob/4edba8ddc3dac088455b8a47ed828dc66c6425e4/api/resources/hives/hives_response.go#L97

Use relative URL instead, please.

Greetings,

**Comment by muesli** [comment]
This is correct. As the README states, it will only listen on loopback until the admin interface and API got an authentication mechanism integrated. This is currently WiP and for security reasons the only currenrtly acceptable compromise.

You can always setup an SSH port forward on your machine in the meantime. Let me know if you need any help with that.

**Comment by toXel** [comment]
Would it be possible to at least make the port configurable? This would really help me because I want to run beehive on a shared host.

**Comment by ad-m** [comment]
@muesli , I understand README. I understand security implication of publishing service without build-in authentication mechanism in Internet. I would like use reverse proxy to provide [authentication](https://httpd.apache.org/docs/2.4/howto/auth.html) and virtual hosts support. I don't have problem with listen on loopback, due using local proxy to publish service eg. https://www.digitalocean.com/community/tutorials/how-to-use-apache-http-server-as-reverse-proxy-using-mod_proxy-extension .

**Comment by muesli** [comment]
@toXel @ad-m Understood, I guess I'll work on making this configurable first then - even without the auth mechanism in place yet.

**Comment by toXel** [comment]
Thank you! I'm looking forward to it :) I already setup an instance on my
Raspberry Pi and configured some chains. This is awesome! This could
definitely replace IFTTT for me as soon as I can host it on a server.
Thanks for this awesome project :)

**Comment by muesli** [comment]
You can now start Beehive like this:

./beehive -bind ":8181" -canonicalurl "http://beehive.myhost.com"

Let me know if this change solves your issues. We should also try and see how it behaves when the canonical URL contains a sub-directory, e.g: "http://myhost.com/beehive"

**Comment by toXel** [comment]
Awesome! That's exactly what I needed :)

**Comment by erguotou520** [comment]
How to setup the environment variable for docker? `canonicalurl `? `beehive_canonicalurl `?

**Comment by leopku** [comment]
@erguotou520 I just had modified Dockerfile for add support for CANNICAL_URL env.
A pr was submitted.
You also can move to https://github.com/leopku/beehive to using it before the pr was accepted.
